name: build

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  android:
    name: Android API ${{ matrix.api-level }} / JDK ${{ matrix.java-version }}
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        api-level:
          - 33
        java-version:
          - 19

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3.3.0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Setup Java ${{ matrix.java-version }}
        uses: actions/setup-java@v3.10.0
        with:
          distribution: temurin
          java-version: ${{ matrix.java-version }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.4.0

      - name: Build Debug APKs and Run lint checks
        run: ./gradlew assembleDebug ktlintCheck lintDebug -Pci -s

      - name: Build Release APKs and Run lint checks
        run: ./gradlew assembleRelease lintRelease -Prelease -Pci -s

      - name: Upload Reports
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Archive-Companion-reports-${{ github.workflow }}-${{ github.run_id }}
          path: |
            app/build/reports
            app/build/test-results
          if-no-files-found: error
          
      - name: Upload Debug .apk artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Archive-Companion-debug-${{ github.workflow }}-${{ github.run_id }}.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error

      - name: Upload Release .apk artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Archive-Companion-release-${{ github.workflow }}-${{ github.run_id }}.apk
          path: app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error

